---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          ref: v1.0.1
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
