name: Read maven version

on: push

jobs:
  read-version:
    name: Read version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run fabasoad/yaml-json-xml-converter-action@v1.0.0
        uses: ./
        id: xml2json
        with:
          path: 'pom.xml'
          from: 'xml'
          to: 'json'
      - name: Print version
        run: |
          sed -e 's%\"%\"%' "${{ steps.xml2json.outputs.data }}" | jq .project._.version | echo