---
name: Convert

on: push

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run fabasoad/yaml-json-xml-converter-action@v1.0.0
        uses: ./
        id: yaml2xml
        with:
          path: 'docker-compose.yml'
          from: 'yaml'
          to: 'xml'
      - name: Print yaml2xml result
        run: echo "${{ steps.yaml2xml.outputs.data }}"
      - name: Run fabasoad/yaml-json-xml-converter-action@v1.0.0
        uses: ./
        id: json2yaml
        with:
          path: 'person.json'
          from: 'json'
          to: 'yaml'
      - name: Print json2yaml result
        run: echo "${{ steps.json2yaml.outputs.data }}"
