---
name: YAML Lint

on:
  push:
    paths:
      - '.github/**.yml'
      - '.yamllint.yml'
      - 'action.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ibiqlik/action-yamllint@v1.0.0
        with:
          config_file: .yamllint.yml
          strict: false
